server:
  port: 8086
  servlet:
    context-path: /api/notifications

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/mergeeats-notifications
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mergeeats.*"

# External Service URLs
services:
  user-service:
    url: http://localhost:8081

# Notification Configuration
notification:
  email:
    enabled: true
    smtp:
      host: ${SMTP_HOST:smtp.gmail.com}
      port: ${SMTP_PORT:587}
      username: ${SMTP_USERNAME:noreply@mergeeats.com}
      password: ${SMTP_PASSWORD:dummy_password}
      auth: true
      starttls: true
  sms:
    enabled: false
    provider: twilio
    account-sid: ${TWILIO_ACCOUNT_SID:dummy}
    auth-token: ${TWILIO_AUTH_TOKEN:dummy}
    from-number: ${TWILIO_FROM_NUMBER:+1234567890}
  push:
    enabled: true
    fcm:
      server-key: ${FCM_SERVER_KEY:dummy_key}
  websocket:
    enabled: true
    endpoint: /ws
  templates:
    order-confirmed: "Your order #{{orderId}} has been confirmed!"
    order-preparing: "Your order #{{orderId}} is being prepared."
    order-out-for-delivery: "Your order #{{orderId}} is out for delivery!"
    order-delivered: "Your order #{{orderId}} has been delivered. Enjoy!"
    order-cancelled: "Your order #{{orderId}} has been cancelled."

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.mergeeats: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"