server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
        
        # Order Service Routes
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0
        
        # Restaurant Service Routes
        - id: restaurant-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/restaurants/**
          filters:
            - StripPrefix=0
        
        # Delivery Service Routes
        - id: delivery-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/delivery/**
          filters:
            - StripPrefix=0
        
        # Payment Service Routes
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0
        
        # Notification Service Routes
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
      
      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: http://localhost:8081/api-docs
      - name: Order Service
        url: http://localhost:8082/api-docs
      - name: Restaurant Service
        url: http://localhost:8083/api-docs
      - name: Delivery Service
        url: http://localhost:8084/api-docs
      - name: Payment Service
        url: http://localhost:8085/api-docs
      - name: Notification Service
        url: http://localhost:8086/api-docs

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"