server:
  port: 8085
  servlet:
    context-path: /api/payments

spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/mergeeats-payments
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mergeeats.*"

# External Service URLs
services:
  user-service:
    url: http://localhost:8081
  order-service:
    url: http://localhost:8082

# Payment Configuration
payment:
  gateway:
    stripe:
      enabled: false
      public-key: ${STRIPE_PUBLIC_KEY:pk_test_dummy}
      secret-key: ${STRIPE_SECRET_KEY:sk_test_dummy}
    razorpay:
      enabled: false
      key-id: ${RAZORPAY_KEY_ID:rzp_test_dummy}
      key-secret: ${RAZORPAY_KEY_SECRET:dummy_secret}
  processing:
    timeout-seconds: 30
    retry-attempts: 3
    refund-timeout-days: 7
  fees:
    platform-fee-percentage: 2.5
    payment-gateway-fee-percentage: 2.9
    min-platform-fee: 5.0
    max-platform-fee: 50.0

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.mergeeats: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"