server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-for-development-only-change-in-production}
  expiration: 86400000 # 24 hours

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.mergeeats.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO 