server:
  port: 8082
  servlet:
    context-path: /api/orders

spring:
  application:
    name: order-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/mergeeats-orders
      auto-index-creation: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mergeeats.*"

# External Service URLs
services:
  user-service:
    url: http://localhost:8081
  restaurant-service:
    url: http://localhost:8083
  payment-service:
    url: http://localhost:8085
  delivery-service:
    url: http://localhost:8084

# Order Processing Configuration
order:
  merge:
    enabled: true
    time-window-minutes: 15
    max-distance-km: 2.0
    max-orders-per-merge: 5
  processing:
    timeout-minutes: 30
    retry-attempts: 3

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.mergeeats: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"