server:
  port: 8084
  servlet:
    context-path: /api/delivery

spring:
  application:
    name: delivery-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/mergeeats-delivery
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: delivery-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mergeeats.*"

# External Service URLs
services:
  user-service:
    url: http://localhost:8081
  order-service:
    url: http://localhost:8082
  restaurant-service:
    url: http://localhost:8083

# Delivery Configuration
delivery:
  assignment:
    max-distance-km: 10.0
    max-orders-per-partner: 5
    auto-assignment-enabled: true
  tracking:
    update-interval-seconds: 30
    location-cache-ttl-minutes: 5
  route:
    optimization-enabled: true
    max-waypoints: 25
    recalculation-threshold-km: 0.5

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.mergeeats: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"